### ISSUE TITLE
[feature_request] dot notation

### ISSUE THREAD

**Issue by Xardas365** [marcinsiedlik/auto_localized#14]
Hi, is possible to implement dot notation for example if We use YAML 

```
general:
  - appName: Flutter Base

homePage:
  - welcome: Welcome!
  - welcome_name: Welcome {1}, {2}!

langPage:
  - test_message: This is a test message in English
```

or JSON
```
{
  "general": [
    {
      "appName": "Flutter Base"
    }
  ],
  "homePage": [
    {
      "welcome": "Welcome!"
    },
    {
      "welcome_name": "Welcome {1}, {2}!"
    }
  ],
  "langPage": [
    {
      "test_message": "This is a test message in English"
    }
  ]
}
```

with nested structure. So that it is possible to call `Strings.homePage.welcome.get()` ?
